name: recovery-dsl
version: 0.1.0.0
github: itsHabib/bakeoff
license: MIT
ghc-options: [-Wall, -Werror]
dependencies:
  - base >= 4.18 && < 5
library:
  source-dirs: src
executables:
  recovery-dsl:
    main: Main.hs
    source-dirs: app
    dependencies: [recovery-dsl]
tests:
  recovery-dsl-test:
    main: Spec.hs
    source-dirs: test
    dependencies: [recovery-dsl]
